steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    cat <<EOF > values.secrets.yaml
    ---
    app:
      minInstances: $_APP_MININSTANCES
    redis:
      password: $(openssl rand -base64 10)
    EOF
- name: 'gcr.io/$PROJECT_ID/helm'
  args: ['repo',
  'update']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=$_CLUSTER_LOCATION'
  - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'
  - 'TILLERLESS=true'
  - 'TILLER_NAMESPACE=${_NAMESPACE}tiller'
- name: 'gcr.io/$PROJECT_ID/helm'
  args: ['dep',
  'update']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=$_CLUSTER_LOCATION'
  - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'
  - 'TILLERLESS=true'
  - 'TILLER_NAMESPACE=${_NAMESPACE}tiller'
- name: 'gcr.io/$PROJECT_ID/helm'
  args: [
  '--install', 
  '$_APP_NAME', 
  '--force', 
  '-f', 
  'values.yaml', 
  '-f',
  'values.secrets.yaml',
  '--namespace', 
  '$_NAMESPACE', 
  './']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=$_CLUSTER_LOCATION'
  - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'
  - 'TILLERLESS=true'
  - 'TILLER_NAMESPACE=${_NAMESPACE}tiller'
substitutions:
    _APP_NAME: 'psp'
    _CLUSTER_NAME: 'psp-cluster-a'
    _CLUSTER_LOCATION: 'us-central1-a'
    _NAMESPACE: 'dev'
    _APP_MININSTANCES: '0'
options:
    substitution_option: 'ALLOW_LOOSE'