apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: mgo-dev
  namespace: dev
spec:
  version: "4.1.7-v2"
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
  terminationPolicy: Delete 