apiVersion: v1
kind: Secret
metadata:
  name: pspsecrets
  namespace: prod
type: Opaque
data:
  redisPassword: {{ required "A valid redis Password is required" .Values.redis.redisPassword | b64enc }}
  jwt_key: WFlaMTIzNjUxOAo=
  # redisPassword: dGVzdDEyMwo=
  # jwt_key: {{ required "A valid JWT key is required" .Values.psp.jwt_key | b64enc }}