apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  redisPassword: {{ required "A valid redis Password is required" .Values.redis.password | b64enc }}
