apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      containers:
      - image: "{{ .Values.psp.image.repository }}:{{ .Values.psp.image.tag }}"
        imagePullPolicy: {{ .Values.psp.image.pullPolicy }}
        env: 
        - name: "PSP_JWT_KEY"
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: "jwt_key"
        - name: "CACHE_SERVER"
          value: "{{ .Release.Name }}-redis-master"
        - name: "CACHE_PORT"
          value: "6379"
        - name: "CACHE_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: redisPassword
        - name: "DB_SERVER"
          value: "mgo-{{ .Release.Namespace }}"
        - name: "DB_PORT"
          value: "27017"
        - name: "DB_USERNAME"
          valueFrom:
            secretKeyRef:
              name: "mgo-{{ .Release.Namepace }}-auth"
              key: username
        - name: "DB_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: "mgo-{{ .Release.Namepace }}-auth"
              key: password