apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{.Release.Name}}-app
spec:
  template:
    metadata:
      annotations:
    spec:
      containers:
      - image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
        imagePullPolicy: {{ .Values.app.image.pullPolicy }}
        env: 
        - name: "JWT_KEY"
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Namespace }}-secrets
              key: "jwtkey"
        - name: "CACHE_SERVER"
          value: "{{ .Release.Name }}-redis-master"
        - name: "CACHE_PORT"
          value: "6379"
        - name: "CACHE_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: redisPassword
        - name: "DB_SERVER"
          value: "mgo-{{ .Release.Namespace }}"
        - name: "DB_PORT"
          value: "27017"
        - name: "DB_USERNAME"
          valueFrom:
            secretKeyRef:
              name: "mgo-{{ .Release.Namespace }}-pulsedb"
              key: username
        - name: "DB_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: "mgo-{{ .Release.Namespace }}-pulsedb"
              key: password
        - name: "EVENTS_SERVER"
          value: "acid-psb-cluster"
        - name: "EVENTS_SERVER_PORT"
          value: "5432"
        - name: "EVENTS_USERNAME"
          value: postgres
        - name: "EVENTS_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: "postgres.acid-psb-cluster.credentials"
              key: password
        - name: "MAIL_USER"
          valueFrom:
            secretKeyRef:
              name: "mailer-{{ .Release.Namespace }}-secrets"
              key: username
        - name: "MAIL_PASS"
          valueFrom:
            secretKeyRef:
              name: "mailer-{{ .Release.Namespace }}-secrets"
              key: password
        - name: "MAIL_FROM"
          valueFrom:
            secretKeyRef:
              name: "mailer-{{ .Release.Namespace }}-secrets"
              key: from