apiVersion: "v1"
kind: "Secret"
metadata:
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: pspsecrets
data:
  redis.redisPassword: {{ required "A valid redis Password is required" .Values.redis.redisPassword | b64enc }}
  psp.jwt_key: {{ required "A valid JWT key is required" .Values.psp.jwt_key | b64enc }}